version: 2

updates:
  # App
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "daily"
    target-branch: "dev"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # For GitHub Actions, set the directory to / to check for workflow files in .github/workflows. (GitHub Docs)
    schedule:
      interval: "daily"
    target-branch: "dev"
