# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/src"
    update_schedule: "daily"
    target_branch: "dev" # Our dev pipeline runs off the dev branch, production runs off of master
    # Requesting reviews from yourself makes Dependabot PRs easy to find (https://github.com/pulls/review-requested)
#    default_reviewers:
#      - "YourGitHubUsername"
    ignored_updates:
      - match:
          dependency_name: "aws-sdk" # To avoid a bunch of pull request spam
          version_requirement: "2.x"
