name: CI / App

on:
  pull_request:
    branches: [dev, stg, prd]
    types: [opened, reopened, synchronize, edited]
    paths:
      - 'src/**'
      - '.github/workflows/ci-app.yml'

env:
  node_version: "22.x"
  FORCE_COLOR: 3

jobs:
  test:
    name: Test
    timeout-minutes: 3
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: npm ci
        working-directory: src
        run: npm ci --prefer-offline

      - name: npm test
        working-directory: src
        run: npm test

      - name: Report test coverage to Codecov
        uses: codecov/codecov-action@v6
        if: env.CODECOV_TOKEN
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  audit:
    name: Audit
    timeout-minutes: 3
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node_version }}

      # We don't need to install deps to audit them

      - name: npm audit
        working-directory: src
        run: npm audit --audit-level=critical

  lint:
    name: Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: npm ci
        working-directory: src
        run: npm ci --prefer-offline

      - name: npm lint
        working-directory: src
        run: npm run lint
